### ISSUE TITLE
Web-gl build/export einrichten

### ISSUE THREAD

**Issue by Athorenz** [VeithBuergerhoff/GameJam-05.23#5]

**Comment by VerticalVeith** [comment]
Das geht [automatisiert](https://game.ci/docs/github/getting-started/), aber wir müssten da ein paar mehr Dinge einrichten (z. B. die Lizenz). Am besten machen wir das einfach manuell.

Zum Bauen muss in den Build Settings (File -> Build Settings) getan werden:
- Alle gewünschten Szenen hinzufügen (oberste wird dann zuerst geladen)
- WebGL auswählen
- Texture Compression: Default
- Dev Build: nur bei Bedarf
- Code Optimization: Speed
- IL2CPP Code Generation: Faster runtime
- dann auf Build und einen leeren Ordner auswählen
